### ISSUE TITLE
No way to change the configs

### ISSUE THREAD

**Issue by neodani** [PrivateBin/helm-chart#12]
Hi!

I have this and I don't see any change in the privatebin UI

```
replicaCount: 2

configs:          
  config.php: |-
    [main]      
      name = "PrivateBinCompany"
      fileupload = true
      discussion = false
```

```
k describe cm privatebin-configs
Name:         privatebin-configs
Namespace:    default
Labels:       app.kubernetes.io/instance=privatebin
              app.kubernetes.io/managed-by=Tiller
              app.kubernetes.io/name=privatebin
              helm.sh/chart=privatebin-0.2.4
Annotations:  <none>

Data
====
config.php:
----
[main]      
  name = "PrivateBinCompany"
  fileupload = true
  discussion = false

```

Its a bug? 

I tried different ways to apply the config but neither works

Thank you

**Comment by bdashrad** [comment]
I'll try to take a look at this tonight.

**Comment by neodani** [comment]
@bdashrad if I change the values.yaml to use `conf.php` doesn't work the pod is crashing, only 
The pod only starts with `config.php`, but you don't see the changes.
```
configs:          
  conf.php: |-
    [main]      
      name = "PrivateBinCompany"
      fileupload = true
      discussion = false
```


```2019/08/27 09:58:45 [error] 9#9: *27 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Exception: PrivateBin requires configuration section [model] to be present in configuration file. in /srv/lib/Configuration.php:121
Stack trace:
#0 /srv/lib/Controller.php(160): PrivateBin\Configuration->__construct()
#1 /srv/lib/Controller.php(121): PrivateBin\Controller->_init()
#2 /var/www/index.php(18): PrivateBin\Controller->__construct()
#3 {main}
  thrown in /srv/lib/Configuration.php on line 121" while reading response header from upstream, client: 10.24.1.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm.sock:", host: "10.24.1.58:80"
10.24.1.1 - - [27/Aug/2019:09:58:45 +0000] "GET / HTTP/1.1" 500 5 "-" "kube-probe/1.13+" "-"
10.24.1.1 - - [27/Aug/2019:09:58:52 +0000] "GET / HTTP/1.1" 500 5 "-" "kube-probe/1.13+" "-"
2019/08/27 09:58:52 [error] 9#9: *29 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Exception: PrivateBin requires configuration section [model] to be present in configuration file. in /srv/lib/Configuration.php:121
Stack trace:
```

**Comment by elrido** [comment]
That one I can answer: If you customize the config, there are a few settings that you can't leave out. You could just take the latest [conf.sample.php](https://github.com/PrivateBin/PrivateBin/blob/master/cfg/conf.sample.php) one and remove all the commented bits (those lines that start with `;`) and adjust the remainder.

What the error is complaining about:
> PrivateBin requires configuration section [model] to be present in configuration file.

is the missing `[model]` section. The minimal default for it would be this:
```ini
[model]
class = Filesystem
[model_options]
dir = PATH "data"
```

**Comment by neodani** [comment]
Thanks! it was that!
